import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';

let a: any = 3;
console.log(a);

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>React Boilerplate</h1>
        <Image alt="react-icon" width="400" height="250" src="/react-gif.gif" />
      </main>
    </div>
  );
};

export default Home;
