import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.logos}>
          <Image
            alt="react-icon"
            width="460"
            height="250"
            src="/react-gif.gif"
          />
        </div>
        <p>Click to learn more about the technologies in this boilerplate:</p>
        <div className={styles.itemList}>
          <a className={styles.item} href="https://www.reactjs.org">
            React
          </a>
          <a className={styles.item} href="https://nextjs.org/">
            NextJS
          </a>
          <a className={styles.item} href="https://www.typescriptlang.org/">
            Typescript
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
